/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package KasirToko.Form;

import KasirToko.Koneksi;
import KasirToko.Model.Kategori;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import javax.swing.JLabel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ariansyah
 */
public class FormKategori extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormKategori.class.getName());

    /**
     * Creates new form FormKategori
     */
    public FormKategori() {
        initComponents();
        buatTampilan();
        tampilData();
    }

    private DefaultTableModel model;
    private JTextField txtNama;

    private void buatTampilan() {
        setTitle("Data Kategori");
        setSize(460, 330);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtNama = new JTextField();
        JButton btnTambah = UiStyle.button("Tambah");
        JButton btnHapus = UiStyle.button("Hapus");
        JPanel atas = new JPanel(new BorderLayout(8, 8));
        atas.setBackground(UiStyle.PANEL);
        atas.setBorder(UiStyle.padding(12, 14, 12, 14));
        atas.add(new JLabel("Nama Kategori"), BorderLayout.WEST);
        atas.add(txtNama, BorderLayout.CENTER);
        atas.add(btnTambah, BorderLayout.EAST);

        model = new DefaultTableModel(new String[]{"Nama Kategori"}, 0);
        JTable tabel = new JTable(model);
        UiStyle.styleTable(tabel);
        JPanel bawah = UiStyle.actionBar();
        bawah.setLayout(new FlowLayout(FlowLayout.RIGHT, 8, 8));
        bawah.add(btnHapus);

        JPanel konten = new JPanel(new BorderLayout(14, 14));
        konten.setBackground(UiStyle.PAGE);
        konten.setBorder(UiStyle.padding(14, 18, 14, 18));
        konten.add(atas, BorderLayout.NORTH);
        konten.add(new JScrollPane(tabel), BorderLayout.CENTER);

        getContentPane().removeAll();
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(UiStyle.header("Master Data Kategori", "Daftar kategori barang"), BorderLayout.NORTH);
        getContentPane().add(konten, BorderLayout.CENTER);
        getContentPane().add(bawah, BorderLayout.SOUTH);

        btnTambah.addActionListener(e -> {
            if (!txtNama.getText().trim().isEmpty()) {
                try {
                    Koneksi.tambahKategori(txtNama.getText().trim());
                    txtNama.setText("");
                    tampilData();
                } catch (IllegalStateException ex) {
                    tampilError(ex);
                }
            }
        });

        btnHapus.addActionListener(e -> {
            int baris = tabel.getSelectedRow();
            if (baris >= 0) {
                try {
                    Koneksi.hapusKategori(model.getValueAt(baris, 0).toString());
                    tampilData();
                } catch (IllegalStateException ex) {
                    tampilError(ex);
                }
            }
        });
    }

    private void tampilData() {
        try {
            model.setRowCount(0);
            for (Kategori kategori : Koneksi.getKategori()) {
                model.addRow(new Object[]{kategori.getNama()});
            }
        } catch (IllegalStateException ex) {
            tampilError(ex);
        }
    }

    private void tampilError(IllegalStateException ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormKategori().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
