/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package KasirToko.Form;

import KasirToko.Koneksi;
import KasirToko.Model.Transaksi;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ariansyah
 */
public class FormLaporan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormLaporan.class.getName());

    /**
     * Creates new form FormLaporan
     */
    public FormLaporan() {
        initComponents();
        buatTampilan();
        tampilData();
    }

    private DefaultTableModel model;

    private void buatTampilan() {
        setTitle("Laporan Transaksi");
        setSize(720, 400);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        model = new DefaultTableModel(new String[]{"No", "Barang", "Jumlah", "Harga", "Total"}, 0);
        JTable tabel = new JTable(model);
        UiStyle.styleTable(tabel);
        JButton btnRefresh = UiStyle.button("Refresh");

        JPanel bawah = UiStyle.actionBar();
        bawah.setLayout(new FlowLayout(FlowLayout.RIGHT, 8, 8));
        bawah.add(btnRefresh);

        JPanel konten = new JPanel(new BorderLayout(14, 14));
        konten.setBackground(UiStyle.PAGE);
        konten.setBorder(UiStyle.padding(14, 18, 14, 18));
        konten.add(new JScrollPane(tabel), BorderLayout.CENTER);

        getContentPane().removeAll();
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(UiStyle.header("Laporan Transaksi", "Rekap transaksi penjualan yang sudah tersimpan"), BorderLayout.NORTH);
        getContentPane().add(konten, BorderLayout.CENTER);
        getContentPane().add(bawah, BorderLayout.SOUTH);

        btnRefresh.addActionListener(e -> tampilData());
    }

    private void tampilData() {
        try {
            model.setRowCount(0);
            for (Transaksi transaksi : Koneksi.getTransaksi()) {
                model.addRow(new Object[]{
                    transaksi.getNomor(),
                    transaksi.getNamaBarang(),
                    transaksi.getJumlah(),
                    transaksi.getHarga(),
                    transaksi.getTotal()
                });
            }
        } catch (IllegalStateException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormLaporan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
